### ISSUE TITLE
PyAutoFit on Blackbox models

### ISSUE THREAD

**Issue by rayadastidar** [Jammy2211/autofit_workspace#3]
Hi! 
I have a model function that relies on an external code and has 15 parameters. Is it possible to use PyAutoFit for parameter estimation?

**Comment by Jammy2211** [comment]
Possibly, are you able too:

Write the model components (e.g. the things with free parameters) as a Python class using the following format:

```
class Gaussian:

    def __init__(
        self,
        centre=0.0,        # <- PyAutoFit recognises these
        normalization=0.1, # <- constructor arguments are
        sigma=0.01,        # <- the Gaussian's parameters.
    ):
        self.centre = centre
        self.normalization = normalization
        self.sigma = sigma
```

And do you have a function which returns a log likelihood from the external code?

It shouldn't be hard to get going, if you send us some code snippets I can help out.

**Comment by rayadastidar** [comment]
I was initially trying to use emcee with fewer parameters. 
For that I defined a model function which uses the external code. The external code requires the input parameters as dictionary.

```
from external_code import run_external_code
def model(x, par1, par2, par3):
    #### par_list is a dictionary that contains all the model parameters
    par_list['model']['par1'] = par1
    par_list['model']['par2'] = par2
    par_list['model']['par3'] = par3
    # this returns a numpy array
    return run_external_code(x, par_list)
```

And defined the log likelihood function this way:    
```
def lnlike(theta, x, y):
    par1, par2, par3 = theta
    m = model(x, *theta)
    return np.sum(norm.logpdf(y, loc=m, scale=np.sqrt(y)))
```

**Comment by Jammy2211** [comment]
I am going to assume `x` and `y` are quantities you have before you begin the fit, let me know if this is not the case.

I think you first want to define a PyAutoFit model component as follows:

```
class ModelComponent: # Give name appropriate to model here

    def __init__(
        self,
        par1 = 0.0,        # <- Keep adding parameters here if
        par2 = 0.1,        # You need more (e.g. 15 values)
        par3 = 0.01,       
    ):
        self.par1 = par1
        self.par2 = par2
        self.par3 = par3
```

You then define an `Analysis` class:

```
class Analysis(af.Analysis):

    def __init__(self, x, y):

        # If you need to pass anything to the `log_likelihood_function` you can add it here.
        
        self.x = x
        self.y = y

    def log_likelihood_function(self, instance):

        #### par_list is a dictionary that contains all the model parameters
        par_list['model']['par1'] = instance.par1
        par_list['model']['par2'] = instance.par2
        par_list['model']['par3'] = instance.par3

        # this returns a numpy array

        m = run_external_code(self.x, par_list)

        return np.sum(norm.logpdf(self.y, loc=m, scale=np.sqrt(self.y)))

```

You can then run:

```
import autofit as af

model = af.Model(ModelComponent)

analysis = Analysis(x=x, y=y)

emcee = af.Emcee(nwalkers=50, nsteps=2000) # This could be DynestyStatic or another search supported by PyAutoFit.

result = emcee.fit(model=model, analysis=analysis)
```

There are neater and more concise ways to set up the model in PyAutoFit, but this is the simplest, so probably worth getting that working before illustrating them.

**Comment by rayadastidar** [comment]
Thanks! I will try out this way.

**Comment by rayadastidar** [comment]
Hi! I have a few more queries.
By defining ModelComponent class like this:
```
class ModelComponent: # Give name appropriate to model here

    def __init__(
        self,
        par1 = 0.0,        # <- Keep adding parameters here if
        par2 = 0.1,        # You need more (e.g. 15 values)
        par3 = 0.01,       
    ):
        self.par1 = par1
        self.par2 = par2
        self.par3 = par3
```
what prior distributions are being assumed for the parameters? 
Can I directly define the desired prior distribution within the ModelComponent class or do I have to use af.Model:
```
model = af.Model(Gaussian)
model.par1 = af.UniformPrior(lower_limit=0.0, upper_limit=1.0)
```

**Comment by Jammy2211** [comment]
> Can I directly define the desired prior distribution within the ModelComponent class

This webpage explains the prior allocation in more detail, in particular how to set up config files to allocate priors by default https://pyautofit.readthedocs.io/en/latest/general/adding_a_model_component.html

But yes, the simplest thing you can do is customize priors as you've shown above, e.g.

```
model = af.Model(ModelComponent)
model.par1 = af.UniformPrior(lower_limit=0.0, upper_limit=1.0)
```

This will work fine, but make sure you do it for every parameter or else you'll get an error (or the prior defaults to a UniformPrior between 0.0 and 1.0!).

You can check the priors via

`print(model.info)`

**Comment by rayadastidar** [comment]
Hi!
 Can I give some starting value for the priors? I am not sure if I missed this somehow in the tutorials.

**Comment by Jammy2211** [comment]
This script shows how to do this:

https://github.com/Jammy2211/autofit_workspace/blob/release/scripts/features/start_point.py

**Comment by rayadastidar** [comment]
Thanks, the initializer seems to work.
I have this one more general query regarding one of the methods used in a notebook.
I was looking at the fit.ipynb notebook within the notebook/simple/overview directory. There a method 'visualize' is defined within the Analysis class to which an argument 'during_analysis' is passed. But I could not find where this argument is used within this method. What I understood is that if this argument is set to True, I should be able to get the plot showing the best-fit model (so far) in an ongoing analysis.

**Comment by Jammy2211** [comment]
During a model-fit, the parameter `during_analysis` is True.

At the end of the fit, it is False.

The purpose is so that during the fit, you can visualize a subset of images (e.g. just the main things that are fast) via `if during_analysis is True:`.

the method `visualize` is called thoruhgout the fit, so yes you can have an updated plotting of the best-fit model. You can ignore `during_analysis` and it'll still do this.

**Comment by rayadastidar** [comment]
Thanks!

I am getting an error which is probably not directly related to PyAutoFit.

I am using DynestyStatic for my Blackbox model. When I run the code, it performs all the iterations, then at this point in the code:
`result = search.fit(model=model, analysis=analysis)`
it shows this info:
`DynestyStatic - INFO - No Dynesty samples found, beginning new non-linear search. `
and returns this error:
`process 1 - ERROR - unsupported operand type(s) for *: 'numpy.ndarray' and 'CompositeUnit'`
tracing back to the line in my code where I am running the external code. The traceback also shows the line in the external code where  the problem is.
I tried using Zeus and got the same error.

As a check, I tried multiplying a numpy.ndarray and a CompositeUnit in the same anaconda environment in python terminal and I did not get this error:
```
>>> import numpy as np
>>> from astropy import units as u
>>> rng = np.random.default_rng()
>>> array = rng.random(10)
>>> array * u.m / u.s / u.kg / u.sr
<Quantity [0.06839098, 0.24331362, 0.31071409, 0.2566943 , 0.40439669,
           0.1330268 , 0.97830936, 0.39107869, 0.34280187, 0.532213  ] m / (kg s sr)>
>>> type(array)
<class 'numpy.ndarray'>
>>> type(u.m / u.s / u.kg / u.sr)
<class 'astropy.units.core.CompositeUnit'>
```

Do you have any suggestions for me on this issue?

**Comment by Jammy2211** [comment]
Is the thing that is a `CompositeUnit` one of the model parameters in the `instance` of the `log_likelihood_function`?

**Comment by rayadastidar** [comment]
Hi!
This issue is arising when I use multiprocessing.
My external code needs a csvy file, which is also produced within the code, and because I used the same file name, this file was constantly getting overwritten. As a result, occasionally partially written/ incomplete files were received by the external code, which caused an error.
Anyway, I really appreciate your help. PyAutofit is indeed a great package and this tutorial is super useful.
